### PR TITLE
Link friend feed

### PR DESCRIPTION
**Pull request by vikramsodhan**
Updated friends feed. 

Ui - based on Alyssa's changes

the logic for adding a friends button added

Only show photos if two users are friends or if the other user's setting is public

### CODE REVIEW

**Review by aditya000028 — APPROVED** [review]
looks good!

**Comment by alyssarusk** [comment]
I'm wondering if we could have this friendship button on the same row as the user's name just to look better
image

**Comment by alyssarusk** [comment]
Also, wondering if we could make the deny request button be apart of the same friendship button as all the other friendship related things? Or is there a reason only deny is its own button?

**Review by alyssarusk — CHANGES_REQUESTED** [review]

**Comment by vikramsodhan** [comment]
> Also, wondering if we could make the deny request button be apart of the same friendship button as all the other friendship related things? Or is there a reason only deny is its own button?

I tried that but we need a separate button because we need to have the option  for denying a friend request as well as accepting one

**Review by alyssarusk — APPROVED** [review]

**Pull request merged**
