### PR TITLE
Create Friend Feed

### LINKED ISSUE #43: Add to profile view activity
This should probably have the following on a profile view view page:

Profile pic
Name
Email
Friend button (add, request sent, etc.)
All Photos grid

Note that this profile view page should be dynamically created, where we can also use this for the edit profile activity in settings. The user should be able to edit profile pic and name if they are looking at their own profile, and should list all photos in a grid underneath. For reference, I think it should be similar to Instagram's profile view page.

### PR DESCRIPTION
**Pull request by alyssarusk**
Now have list of friend's photos and can click on them for detail page.

Currently if there isn't a photo a default "No fit found" is displayed because it's hard to delete the row cleanly but if someone knows a way we can change it.

Closes #43

### CODE REVIEW

**Review by janetahn — APPROVED** [review]
looks good to me, i'm assuming we only see like the 5 most recent days??

**Comment by janetahn** [comment]
i was originally thinking like we see their calendar view but maybe thats too intense

**Comment by alyssarusk** [comment]
> looks good to me, i'm assuming we only see like the 5 most recent days??

Nope its actually every day starting from nov 30 and onwards. Thats why I used recyclerview bc its better about loading things quicker

**Comment by alyssarusk** [comment]
> i was originally thinking like we see their calendar view but maybe thats too intense

yeah there was a bunch of views I think would look better but idk how to get a decent load time on them

**Pull request merged**
